name: Jekyll Site CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # 设置 Ruby 环境
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.x'  # 替换成你需要的 Ruby 版本

    # 安装 bundler
    - name: Install Bundler
      run: gem install bundler

    # 安装项目依赖
    - name: Install Dependencies
      run: bundle install

    # 构建 Jekyll 网站
    - name: Build Jekyll Site
      run: bundle exec jekyll build

    # 上传构建的 _site 目录
    - name: Upload _site Directory
      uses: actions/upload-artifact@v3  # 更新为 v3
      with:
        name: site
        path: ./_site